development:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_production
  pool: 5

